# 全局通用设置
[general]
retry_times = 3                    # 请求失败重试次数
backoff_factor = 2.0
timeout = 30.0                     # 页面加载超时时间 (秒)
max_connections = 10               # 并发连接的最大数
max_rps = 1.0                      # 最大请求速率 (requests per second), 如不设置则请设置一个较大的数或负数
request_interval = 2.0             # 同一本书各章节请求间隔 (秒)
raw_data_dir = "./raw_data"        # 原始章节 JSON/DB 存放目录
output_dir = "./downloads"         # 最终输出文件存放目录
cache_dir = "./novel_cache"        # 本地缓存目录 (字体 / 图片等)
workers = 2                        # 工作协程数
skip_existing = true               # 是否跳过已存在章节
storage_batch_size = 1             # SQLite 批量提交的章节数量
locale_style = "simplified"        # simplified / traditional

[general.debug]
save_html = false                  # 是否将抓取到的原始 HTML 保留到磁盘
log_level = "INFO"                 # 日志级别: DEBUG, INFO, WARNING, ERROR

[general.font_ocr]
decode_font = false                # 是否尝试本地解码混淆字体
batch_size = 32
save_font_debug = false            # 是否保存字体解码调试数据

# 各站点的特定配置
[sites.qidian]  # 起点中文网
book_ids = [
  "0000000000",
  "0000000000"
]
login_required = true              # 是否需要登录才能访问
use_truncation = true              # 是否基于章节长度截断以避免重复内容

[sites.esjzone]  # ESJ Zone
book_ids = [
  "0000000000",
  "0000000000"
]
login_required = true
# username = "youremail@domain.com"  # 登录邮箱
# password = "yourpassword"          # 登录密码

[sites.linovelib]  # 哔哩轻小说
book_ids = [
  "0000000000",
  "0000000000"
]
split_mode = "book"                # 导出方式: book / volume
login_required = false

[sites.common]
login_required = false

# 输出文件格式及相关选项
[output.formats]
make_txt = true                    # 是否生成完整 TXT 文件
make_epub = true                   # 是否生成 EPUB

[output.naming]
append_timestamp = false           # 在文件名中追加时间戳
filename_template = "{title}_{author}"  # 文件命名规则

[output.epub]
include_cover = true               # 是否在 EPUB 中包含封面
include_picture = true             # 是否下载章节图片 (体积较大)

[cleaner]
clean_text = false                 # 是否对章节文本做清理
remove_invisible = true

[cleaner.title]
remove_patterns = [
  '【[^】]*?】',
  '[(（][^()（）]*?求票[^()（）]*?[)）]',
]

[cleaner.title.replace]
'：' = ':'

[cleaner.title.external]
enabled = false
remove_patterns = "path/to/title-remove.json"
replace         = "path/to/title-replace.json"

[cleaner.content]
remove_patterns = []

[cleaner.content.replace]
'li子' = '例子'
'pinbi词' = '屏蔽词'

[cleaner.content.external]
enabled = false
remove_patterns = "path/to/content-remove.json"
replace         = "path/to/content-replace.json"
