#!/usr/bin/env python3
"""
novel_downloader.apps.constants
-------------------------------

"""

# -----------------------------------------------------------------------------
# Supported map
# -----------------------------------------------------------------------------

DOWNLOAD_SUPPORT_SITES = {
    # "aaatxt": "3A电子书 (aaatxt)",
    "akatsuki_novels": "暁 (akatsuki_novels)",
    "alicesw": "爱丽丝书屋 (alicesw)",
    "alphapolis": "アルファポリス (alphapolis)",
    "b520": "笔趣阁 (b520)",
    "biquge5": "笔趣阁 (biquge5)",
    "biquge345": "笔趣阁 (biquge345)",
    "biquguo": "笔趣阁小说网 (biquguo)",
    # "biquyuedu": "精彩小说 (biquyuedu)",
    "bixiange": "笔仙阁 (bixiange)",
    "blqudu": "笔趣读 (blqudu)",
    "bxwx9": "笔下文学网 (bxwx9)",
    "ciluke": "思路客 (ciluke)",
    "ciyuanji": "次元姬小说网 (ciyuanji)",
    "czbooks": "小说狂人 (czbooks)",
    "dushu": "读书 (dushu)",
    "dxmwx": "大熊猫文学网 (dxmwx)",
    "esjzone": "ESJ Zone (esjzone)",
    "fanqienovel": "番茄小说网 (fanqienovel)",
    "fsshu": "笔趣阁 (fsshu)",
    "guidaye": "名著阅读 (guidaye)",
    "hetushu": "和图书 (hetushu)",
    "hongxiuzhao": "红袖招 (hongxiuzhao)",
    "i25zw": "25中文网 (i25zw)",
    "ixdzs8": "爱下电子书 (ixdzs8)",
    "jpxs123": "精品小说网 (jpxs123)",
    "kadokado": "KadoKado (kadokado)",
    "ktshu": "八一中文网 (ktshu)",
    "kunnu": "鲲弩小说 (kunnu)",
    "laoyaoxs": "老幺小说网 (laoyaoxs)",
    "lewenn": "乐文小说网 (lewenn)",
    "linovel": "轻之文库 (linovel)",
    "linovelib": "哔哩轻小说 (linovelib)",
    "lnovel": "轻小说百科 (lnovel)",
    "lvsewx": "绿色小说网 (lvsewx)",
    "mangg_com": "追书网.com (mangg_com)",
    "mangg_net": "追书网.net (mangg_net)",
    "mjyhb": "三五中文 (mjyhb)",
    "n8novel": "无限轻小说 (n8novel)",
    # "n8tsw": "笔趣阁 (n8tsw)",
    "n17k": "17K小说网 (n17k)",
    "n23ddw": "顶点小说网 (n23ddw)",
    "n23qb": "铅笔小说 (n23qb)",
    "n37yq": "三七轻小说 (n37yq)",
    "n37yue": "37阅读网 (n37yue)",
    "n69hao": "69书吧 (n69hao)",
    "n69shuba": "69书吧 (n69shuba)",
    # "n69yue": "69阅读 (n69yue)",
    "n71ge": "新吾爱文学 (n71ge)",
    "n101kanshu": "101看书 (n101kanshu)",
    "novelpia": "ノベルピア (novelpia)",
    "piaotia": "飘天文学网 (piaotia)",
    "pilibook": "霹雳书屋 (pilibook)",
    "qbtr": "全本同人小说 (qbtr)",
    "qidian": "起点中文网 (qidian)",
    "qqbook": "QQ阅读 (qqbook)",
    "quanben5": "全本小说网 (quanben5)",
    "ruochu": "若初文学网 (ruochu)",
    "sfacg": "SF轻小说 (sfacg)",
    "shaoniandream": "少年梦 (shaoniandream)",
    "shauthor": "大众文学 (shauthor)",
    "shencou": "神凑轻小说 (shencou)",
    "shu111": "书林文学 (shu111)",
    "syosetu": "小説家になろう (syosetu)",
    "syosetu18": "小説家になろう (syosetu18)",
    "syosetu_org": "ハーメルン (syosetu_org)",
    "shuhaige": "书海阁小说网 (shuhaige)",
    "tianyabooks": "天涯书库 (tianyabooks)",
    "tongrenquan": "同人圈 (tongrenquan)",
    "tongrenshe": "同人社 (tongrenshe)",
    "trxs": "同人小说网 (trxs)",
    "ttkan": "天天看小说 (ttkan)",
    "twkan": "台灣小說網 (twkan)",
    "uaa": "有爱爱 (uaa)",
    # "wanbengo": "完本神站 (wanbengo)",
    "wenku8": "轻小说文库 (wenku8)",
    # "xiaoshuoge": "小说屋 (xiaoshuoge)",
    "xiguashuwu": "西瓜书屋 (xiguashuwu)",
    "westnovel": "西方奇幻小说网 (westnovel)",
    "westnovel_sub": "西方奇幻小说网 (westnovel_sub)",
    "wxsck": "万相书城 (wxsck)",
    # "xs63b": "小说路上 (xs63b)",
    "xshbook": "小说虎 (xshbook)",
    "yamibo": "百合会 (yamibo)",
    "yibige": "一笔阁 (yibige)",
    "yodu": "有度中文网 (yodu)",
    "zhenhunxiaoshuo": "镇魂小说网 (zhenhunxiaoshuo)",
}

SEARCH_SUPPORT_SITES = {
    # "aaatxt": "3A电子书",
    "alicesw": "爱丽丝书屋",
    "b520": "笔趣阁 (b520)",
    "biquge5": "笔趣阁 (biquge5)",
    "biquguo": "笔趣阁小说网",
    "bxwx9": "笔下文学网",
    "ciluke": "思路客",
    "ciyuanji": "次元姬小说网",
    "czbooks": "小说狂人",
    "dxmwx": "大熊猫文学网",
    "esjzone": "ESJ Zone",
    "fsshu": "笔趣阁 (fsshu)",
    "hetushu": "和图书",
    "i25zw": "25中文网",
    "ixdzs8": "爱下电子书",
    "jpxs123": "精品小说网",
    "kadokado": "KadoKado",
    "ktshu": "八一中文网",
    "laoyaoxs": "老幺小说网",
    "linovel": "轻之文库",
    "mangg_net": "追书网.net",
    "n8novel": "无限轻小说",
    "n23ddw": "顶点小说网",
    "n23qb": "铅笔小说",
    "n37yq": "三七轻小说",
    "n37yue": "37阅读网",
    # "n69yue": "69阅读",
    "n71ge": "新吾爱文学",
    "n101kanshu": "101看书",
    "piaotia": "飘天文学网",
    "qbtr": "全本同人小说",
    "qidian": "起点中文网",
    "quanben5": "全本小说网",
    "shuhaige": "书海阁小说网",
    "tongrenquan": "同人圈",
    "tongrenshe": "同人社",
    "trxs": "同人小说网",
    "ttkan": "天天看小说",
    # "wanbengo": "完本神站",
    # "xiaoshuoge": "小说屋",
    "xiguashuwu": "西瓜书屋",
    # "xs63b": "小说路上",
    "xshbook": "小说虎",
    "yodu": "有度中文网",
}
