name: Site Request
description: Request support for a new site / 请求支持新站点
title: "[Site] "
labels: ["site-request"]
body:
  - type: input
    id: site_name
    attributes:
      label: Site Name / 站点名称
    validations:
      required: true

  - type: input
    id: site_url
    attributes:
      label: Site URL / 站点链接
      placeholder: "https://example.com"
    validations:
      required: true

  - type: input
    id: site_type
    attributes:
      label: Site Type / 站点类型
      description: |
        Provide the content type category, such as:
        - original / 原创
        - reprint / 转载
        - light novel / 轻小说
        - manga / 漫画
        - fanfic / 同人
        - forum / 论坛
        请填写站点所属的类型，以上为示例，可自由填写。
      placeholder: "e.g. 原创 / 转载 / 轻小说"
    validations:
      required: true

  - type: textarea
    id: site_description
    attributes:
      label: Site Description / 站点描述
      description: Basic introduction to the site. / 简单介绍一下这个站点。

  - type: dropdown
    id: requires_login
    attributes:
      label: Login Required for Some Chapters? / 是否有部分章节需要登录
      options:
        - Yes / 是
        - No / 否
      description: |
        Does the site restrict some chapters behind login?
        此站点是否有部分章节需要登录后才能查看？
    validations:
      required: true

  - type: dropdown
    id: app_only
    attributes:
      label: Some Chapters App-Only? / 是否有部分章节仅限 App 端浏览
      options:
        - Yes / 是
        - No / 否
      description: |
        Are some chapters available only in the app (not web)?
        是否存在只能在 App 中访问、网页端不可见的章节？
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why should this site be added? / 希望添加该站点的理由
      description: Explain why support for this site is important. / 请说明添加此站点的原因。
    validations:
      required: true
