name: Publish Python Package

on:
  workflow_run:
    workflows: ["Tag After Bump"]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade build twine

      - name: Fix README.md links for PyPI
        run: |
          sed -i 's#](docs/#](https://github.com/saudadez21/novel-downloader/blob/main/docs/#g' README.md

      - name: Compile translations
        run: |
          pip install babel
          pybabel compile -d src/novel_downloader/locales

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
